export const ACTION_MAIN_VIEW = 'ACTION_MAIN_VIEW';
export const ACTION_VIEW_TODO = 'ACTION_VIEW_TODO';
export const ACTION_EDIT_TODO = 'ACTION_EDIT_TODO';
export const ACTION_NEW_TODO = 'ACTION_NEW_TODO';
